"""
NexSandglass — 第二层：投石问路 + 解密读取
===========================================
import sandglass_vault
results = sandglass_vault.search("关键词")
latest = sandglass_vault.recent(5)
"""

import base64
import logging
import mmap
import os
import re
from datetime import datetime

from sandglass_paths import _NB

_SANDGLASS = os.path.join(_NB, "sandglass.txt")
_IDX = os.path.join(_NB, "sandglass.idx")

logger = logging.getLogger(__name__)


def set_idx_path(path: str):
    """重定向投石问路索引路径——基准测试用。"""
    global _IDX
    _IDX = path

try:
    from win32crypt import CryptUnprotectData
except ImportError:
    CryptUnprotectData = None

# ── idx 内存缓存（偷师 memory-os：O(1) 查 token）──
_idx_cache: dict | None = None
_idx_mtime: float = 0


# ═══════════════════════════════════════════════
# 投石问路
# ═══════════════════════════════════════════════

def _tokenize(text: str) -> set:
    """通用分词：中文2字词+英文2+字母+英文3-4字符滑动窗口（n-gram）。
    不索引单汉字（高频噪音）。"""
    tokens = set()
    t = text.lower()
    # 英文词（2+字母）
    tokens.update(re.findall(r"[a-zA-Z0-9_]{2,}", t))
    # 英文字符滑动窗口——2到4字窗口，覆盖"sup/up/port/grou/oup"等子串
    eng = "".join(re.findall(r"[a-z0-9]", t))
    for n in (2, 3, 4):
        for i in range(len(eng) - n + 1):
            tokens.add(eng[i:i + n])
    # 中文2字词
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    for i in range(len(chars) - 1):
        tokens.add(chars[i : i + 2])
    return {t for t in tokens if t}


def _query_tokens(text: str) -> set:
    """搜索分词：和_tokenize相同，但单字仅当输入只有一个中文字时才保留。"""
    tokens = _tokenize(text)
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    if len(chars) != 1:
        tokens -= set(chars)  # 去单字
    return tokens


def _decrypt(text: str) -> str:
    """DPAPI 解密。失败尝试 base64 解码（非 Windows 降级存储）。"""
    text = text.strip()
    if not text.startswith("AQAA"):
        if CryptUnprotectData is None:
            # 非 Windows：base64 编码存储，尝试解码
            try:
                return base64.b64decode(text).decode("utf-8")
            except Exception:
                return text
        return text
    if not CryptUnprotectData:
        return text
    try:
        raw = base64.b64decode(text)
        return CryptUnprotectData(raw, None, None, None, 0)[1].decode("utf-8")
    except Exception:
        return text


def _parse_line(line: str) -> tuple:
    """返回 (ts, sender, decrypted_text) 或 (None, None, None)。"""
    if " | " not in line:
        return None, None, None
    parts = line.strip().split(" | ", 2)
    if len(parts) < 3:
        return None, None, None
    return parts[0], parts[1], _decrypt(parts[2])


def _write_idx(idx):
    """Write idx dict to sandglass.idx file (atomic replace)."""
    tmp = _IDX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED BY NEXSANDGLASS — DO NOT EDIT\n")
        f.write("# token:line_number,line_number,...\n")
        f.write("# delete this file and run rebuild_index() to regenerate\n")
        f.write("\n")
        for token in sorted(idx):
            f.write(f"{token}:{','.join(map(str, sorted(set(idx[token]))))}\n")
    os.replace(tmp, _IDX)


def rebuild_index() -> int:
    """全量重建投石问路（基于解密后文本）。原子写。返回词条数。"""
    global _idx_cache
    _idx_cache = None
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        idx = {}
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                ts, sender, text = _parse_line(line)
                if not ts:
                    continue
                for token in _tokenize(text):
                    idx.setdefault(token, []).append(n)

        _write_idx(idx)
        return len(idx)
    except Exception:
        logger.warning("sandglass: rebuild_index() failed", exc_info=True)
        return 0


def _sync_index() -> dict:
    """增量更新索引并返回内存 dict。利用缓存避免重复读盘。"""
    global _idx_cache

    try:
        if not os.path.exists(_SANDGLASS):
            _idx_cache = {}
            return {}

        total = 0
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            total = sum(1 for _ in f)

        # 缓存命中：mtime未变 + 最大行号 ≥ 总行数
        if _idx_cache is not None:
            try:
                cur_mtime = os.path.getmtime(_SANDGLASS)
                if cur_mtime != _idx_mtime:
                    _idx_cache = None  # 文件被修改过，清缓存
                    return {}  # 返回空，让调用方重建
            except Exception:
                pass  # mtime 不可用，沿用缓存
            if _idx_cache is not None:
                cached_max = 0
                for lines in _idx_cache.values():
                    if lines:
                        cached_max = max(cached_max, max(lines))
                if cached_max >= total and total > 0:
                    return _idx_cache

        # 读 idx
        idx = {}
        idx_max = 0
        if os.path.exists(_IDX):
            with open(_IDX, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("#") or ":" not in line:
                        continue
                    t, rest = line.strip().split(":", 1)
                    nums = [int(x) for x in rest.split(",") if x]
                    idx[t] = nums
                    if nums:
                        idx_max = max(idx_max, max(nums))

        if idx_max and total > 0 and idx_max > total:
            logger.warning(f"sandglass: idx行号({idx_max})超过沙漏总行数({total})，可能是手动编辑了idx文件。自动重建中...")
            return {}  # 返回空 → 触发 mmap 降级搜索。下次 rebuild_index() 会自动重建。

        if idx_max >= total:
            _idx_cache = idx
            return idx

        # 增量：追加新行
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                if n <= idx_max:
                    continue
                ts, sender, text = _parse_line(line)
                if not ts:
                    continue
                for token in _tokenize(text):
                    idx.setdefault(token, []).append(n)

        # 原子写
        _write_idx(idx)

        # LRU驱逐——超过5000词条时清缓存重建（防止无限膨胀）
        if len(idx) > 5000:
            _idx_cache = {}
            return {}
        _idx_cache = idx
        try: _idx_mtime = os.path.getmtime(_SANDGLASS)
        except Exception: pass
        return idx

    except Exception:
        logger.warning("sandglass: _sync_index() failed", exc_info=True)
        return _idx_cache if _idx_cache else {}


# ═══════════════════════════════════════════════
# 搜索 + 读取
# ═══════════════════════════════════════════════

def search(query: str, limit: int = 10, month: str = "") -> list:
    """搜索沙漏。返回 [(行号, 时间, 明文), ...]。
    委托给 SearchRouter 三层架构——影子沙→投石问路→mmap。"""
    try:
        from search_router import SearchRouter, ShadowSearch, IdxFtsSearch, MmapFallback
        router = SearchRouter(
            ShadowSearch(_SANDGLASS),
            IdxFtsSearch(_SANDGLASS, _IDX),
            MmapFallback(_SANDGLASS)
        )
        return router.search(query, limit)
    except Exception:
        return _legacy_search(query, limit, month)


def _legacy_search(query, limit, month):
    try:
        if not os.path.exists(_SANDGLASS):
            return []

        # ── 影子沙优先（脱口而出层） ──
        try:
            from shadow_sand import shadow_search as _shadow_search, shadow_retrieval_bump, shadow_boost, shadow_boost
            shadow_hits = _shadow_search(query, limit)
            if shadow_hits:
                results = []
                with open(_SANDGLASS, "r", encoding="utf-8") as f:
                    for n, line in enumerate(f, 1):
                        for score, ln in shadow_hits:
                            if n == ln:
                                ts, sender, text = _parse_line(line)
                                if ts and text:
                                    results.append((ln, ts, text))
                        if len(results) >= limit:
                            break
                if results:
                    shadow_retrieval_bump([ln for _, ln in shadow_hits[:limit]])
                    # 信任阈值——最佳匹配<0.5时，和FTS5混合精排
                    best_trust = shadow_hits[0][0] if shadow_hits else 0
                    if best_trust < 0.5:
                        try:
                            from sandglass_sqlite import search_in, sync_incremental
                            sync_incremental()
                            shadow_lns = [ln for _, ln in shadow_hits[:20]]
                            fts_ranked = search_in(shadow_lns, query)
                            if fts_ranked:
                                # 混合排序：信任分 + FTS5排名
                                scored = []
                                for fid, ts2, txt in fts_ranked[:limit]:
                                    trust = next((s for s, ln in shadow_hits if ln == fid), 0.5)
                                    scored.append((trust * 0.6 + 0.4, fid, ts2, txt))
                                scored.sort(key=lambda x: x[0], reverse=True)
                                return [(ln, ts2, txt) for _, ln, ts2, txt in scored[:limit]]
                        except: pass
                    return results
        except Exception:
            pass

        # ── 投石问路 → FTS5精排（第二层串联） ──
        # idx 快速定位候选行号，FTS5/五维权重精排
        candidate_lines = set()
        try:
            idx = _sync_index()
            if not idx:
                rebuild_index()
                idx = _sync_index()
            if idx:
                q_tokens = _query_tokens(query)
                for token in q_tokens:
                    if token in idx:
                        candidate_lines.update(idx[token])
        except Exception:
            pass

        # ── 双模式搜索（FTS5 + mmap） ──
        try:
            from sandglass_think import search_filter, offset_guide
            filt = search_filter(query)
            # 偏移引导：搜索后挂载偏移方向（先拿 filt 再挂 guide）
            try:
                guide = offset_guide(query)
                if guide.get("bias") and guide["bias"] != "neutral":
                    filt["offset_guide"] = guide
            except Exception:
                pass
            has_llm = filt.get("source", "").startswith("LLM")

            # 投石问路先行——如果有候选行号，FTS5只在候选行内精排
            if candidate_lines:
                try:
                    from sandglass_sqlite import search_in, sync_incremental
                    sync_incremental()
                    ranked = search_in(list(candidate_lines), query)
                    if ranked:
                        line_nums = [r[0] for r in ranked[:limit]]
                        # 五维权重排序
                        results = []
                        with open(_SANDGLASS, "r", encoding="utf-8") as f:
                            for n, line in enumerate(f, 1):
                                if n in line_nums:
                                    ts, sender, text = _parse_line(line)
                                    if ts and text:
                                        results.append((n, ts, text))
                        if results:
                            try:
                                from sandglass_think import search_filter
                                sf = search_filter(query)
                                weights = sf.get("weights", {})
                                if weights:
                                    scored = []
                                    for ln, ts, text in results:
                                        score = sum(weights.get(w, 1.0) for w in _query_tokens(text) if w in weights)
                                        scored.append((score, (ln, ts, text)))
                                    scored.sort(key=lambda x: x[0], reverse=True)
                                    results = [item for _, item in scored]
                            except: pass
                            return results[:limit]
                except Exception:
                    pass  # 投石问路+FTS5失败，继续走全量FTS5

            # 默认搜近一年——缩小范围加速
            if not month:
                # 如果有时间范围感知，用第一个年份
                time_range = filt.get("time_range", [])
                if time_range:
                    month = time_range[0]  # 用最早年份做前缀匹配
                else:
                    month = datetime.now().strftime("%Y")

            if has_llm and len(filt.get("keywords", [])) > 1:
                # LLM模式：扩展关键词 → mmap全量初筛 → FTS5排序 → idx精排
                line_nums = set()
                for kw in filt["keywords"][:8]:
                    for ln, ts, text in _mmap_search(kw, limit=-1, month=""):
                        line_nums.add(ln)
                if line_nums:
                    from sandglass_sqlite import search_in, sync_incremental
                    sync_incremental()
                    ranked = search_in(list(line_nums), query)
                    if ranked:
                        line_nums = [r[0] for r in ranked]

            else:
                # 无LLM模式：FTS5全量 → idx精排
                from sandglass_sqlite import search as fts_search, sync_incremental, search_year
                sync_incremental()
                candidates = search_year(query, month, limit=200) if month else fts_search(query, limit=200)
                line_nums = set(c[0] for c in candidates) if candidates else set()

            # idx 精排（共用）
            if line_nums:
                idx = _sync_index()
                if idx:
                    tokens = _query_tokens(query)
                    if tokens:
                        # 转 set 加速——O(1) 查找
                        idx_set = {t: set(lns) for t, lns in idx.items() if t in tokens}
                        scored = [(ln, sum(1 for t in tokens if ln in idx_set.get(t, set()))) for ln in line_nums]
                        scored.sort(key=lambda x: x[1], reverse=True)
                        line_nums = set(s[0] for s in scored[:limit])

                # 回读全文
                results = []
                with open(_SANDGLASS, "r", encoding="utf-8") as f:
                    for n, line in enumerate(f, 1):
                        if n in line_nums:
                            ts, sender, text = _parse_line(line)
                            if ts and (not month or ts.startswith(month)):
                                results.append((n, ts, text))
                                if len(results) >= limit: break
                if results:
                    return results

            # mmap 全量暴力 → FTS5 精排(≤200) → 兜底
            mmap_results = _mmap_search(query, 500, month, stage_filter=True)
            if mmap_results:
                from sandglass_sqlite import search_in, sync_incremental
                sync_incremental()
                line_nums = [r[0] for r in mmap_results[:500]]
                ranked = search_in(line_nums, query)
                if ranked:
                    line_nums = [r[0] for r in ranked[:limit]]
                    results = []
                    with open(_SANDGLASS, "r", encoding="utf-8") as f:
                        for n, line in enumerate(f, 1):
                            if n in line_nums:
                                ts, sender, text = _parse_line(line)
                                if ts and text:
                                    results.append((n, ts, text))
                                    if len(results) >= limit: break
                    if results: return results
            return []
        except Exception:
            pass
        if not os.path.exists(_IDX):
            rebuild_index()
        else:
            _sync_index()

        tokens = _query_tokens(query)
        if not tokens:
            return []

        idx = _sync_index()
        if not idx:
            # ── 三级降级：mmap 直接内存搜索 ──
            return _mmap_search(query, limit, month)

        line_scores: dict = {}
        for token in tokens:
            for ln in idx.get(token, []):
                line_scores[ln] = line_scores.get(ln, 0) + 1

        if not line_scores:
            return _mmap_search(query, limit, month)

        results = []
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                if n not in line_scores:
                    continue
                ts, sender, text = _parse_line(line)
                if not ts:
                    continue
                if month and not ts.startswith(month):
                    continue
                results.append((n, ts, text, line_scores[n]))

        # ── 匹配数降序 → 行号降序（最新优先）──
        results.sort(key=lambda x: (x[3], x[0]), reverse=True)
        return [(n, ts, text) for n, ts, text, _ in results[:limit]]

    except Exception:
        logger.warning("sandglass: search(%r) failed", query, exc_info=True)
        return []


def recent(n: int = 10) -> list:
    """最近 N 条。[(行号, 时间, 明文), ...]"""
    try:
        if n <= 0 or not os.path.exists(_SANDGLASS):
            return []
        from collections import deque
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            all_lines = f.readlines()
        total = len(all_lines)
        last_lines = deque(all_lines, n)
        results = []
        for i, line in enumerate(last_lines):
            ts, sender, text = _parse_line(line)
            if not ts:
                continue
            ln = total - len(last_lines) + i + 1
            results.append((ln, ts, text))
        return results
    except Exception:
        logger.warning("sandglass: recent(%d) failed", n, exc_info=True)
        return []


def count() -> int:
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            return sum(1 for _ in f)
    except Exception:
        logger.warning("sandglass: count() failed", exc_info=True)
        return 0


def _mmap_search(query: str, limit: int, month: str, stage_filter: bool = False) -> list:
    """三级降级：mmap 直接内存搜索。stage_filter=True 时只扫当前阶段+上一阶段。"""
    results = []
    try:
        # 阶段过滤——缩小扫描范围
        scan_months = [month]
        if stage_filter:
            try:
                from sandglass_think import _current_stage, stage_list
                current = _current_stage()
                scan_months = [current]
                stages = stage_list()
                if len(stages) >= 2:
                    scan_months.append(stages[-2].get("name", current))
            except: pass
        with open(_SANDGLASS, "rb") as f:
            with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
                line_start = 0; line_num = 0
                while line_start < len(mm):
                    line_end = mm.find(b"\n", line_start)
                    if line_end == -1: line_end = len(mm)
                    line_num += 1
                    line = mm[line_start:line_end].decode("utf-8", errors="replace")
                    ts, sender, text = _parse_line(line)
                    if ts and query.lower() in text.lower():
                        if not month or ts.startswith(month):
                            results.append((line_num, ts, text))
                            if limit > 0 and len(results) >= limit: break
                    line_start = line_end + 1
    except Exception:
        pass
    return results


# ═══════════════════════════════════════════════
# 时间回溯
# ═══════════════════════════════════════════════

def timeline(query: str) -> dict:
    """时间回溯——按年份分层返回关键词的演变轨迹。"""
    try:
        all_results = search(query, limit=10000)
        if not all_results:
            return {}
        # 按行号升序（时间顺序），而非 reverse search 的匹配数排序
        all_results.sort(key=lambda x: x[0])

        years = {}
        for ln, ts, text in all_results:
            year = ts[:4]
            if year not in years:
                years[year] = {"count": 0, "earliest": text, "earliest_at": ts, "latest": text, "latest_at": ts}
            years[year]["count"] += 1
            years[year]["latest"] = text
            years[year]["latest_at"] = ts

        result = {}
        for year in sorted(years):
            y = years[year]
            result[year] = {"count": y["count"], "earliest": y["earliest"], "earliest_at": y["earliest_at"],
                            "latest": y["latest"], "latest_at": y["latest_at"]}
        return result
    except Exception:
        logger.warning("sandglass: timeline(%r) failed", query, exc_info=True)
        return {}
