"""
NexSandglass — 第二层：投石问路 + 解密读取
===========================================
import sandglass_vault
results = sandglass_vault.search("关键词")
latest = sandglass_vault.recent(5)
"""

from __future__ import annotations

import logging
import mmap
import os
import re
from datetime import datetime

from nexsandglass.core.sandglass_paths import _NB

_SANDGLASS = os.path.join(_NB, "sandglass.txt")
_IDX = os.path.join(_NB, "sandglass.idx")

logger = logging.getLogger(__name__)

# ═══════ B1 直写治理：NYX_ENFORCE_RUNTIME=1 时检测非 orchestrator 直写 ═══════
_ALLOWED_DIRECT = ("orchestrator", "runtime", "facade", "sandglass_mcp", "memory_provider",
                   "shadow_sand", "weavethread", "bridge", "recall_writer", "search_router",
                   "sandglass_vault", "sandglass_log", "sandglass_think", "sandglass_sqlite",
                   "temporal_fact", "consolidation", "promotion", "intent", "bundle")


def _enforce_runtime(entry: str) -> None:
    """开发模式直写治理：检测调用栈，非 orchestrator 直写则 warning/metrics。

    NYX_ENFORCE_RUNTIME=1 时生效；不阻断（仅告警），CI 可 grep 告警日志发现新增直写。
    """
    if os.environ.get("NYX_ENFORCE_RUNTIME") != "1":
        return
    try:
        import inspect
        stack = inspect.stack()
        # 向上找第一个非本模块的调用者
        for frame in stack[1:]:
            mod = frame.filename
            caller = ""
            for part in mod.replace("\\", "/").split("/"):
                if part.endswith(".py"):
                    caller = part[:-3]
                    break
            if caller and caller not in _ALLOWED_DIRECT:
                logger.warning(
                    "[B1 直写治理] %s 被非 orchestrator 模块直写: %s (NYX_ENFORCE_RUNTIME=1)",
                    entry, caller,
                )
                return
    except Exception:
        pass

def set_idx_path(path: str):
    """重定向投石问路索引路径——基准测试用。"""
    global _IDX
    _IDX = path

# ── idx 内存缓存（偷师 memory-os：O(1) 查 token）──
_idx_cache: dict | None = None
_idx_mtime: float = 0


# ═══════════════════════════════════════════════
# 投石问路
# ═══════════════════════════════════════════════

def _tokenize(text: str) -> set:
    """通用分词：中文2字词+英文2+字母+英文3-4字符滑动窗口（n-gram）。
    不索引单汉字（高频噪音）。"""
    tokens = set()
    t = text.lower()
    # 英文词（2+字母）
    tokens.update(re.findall(r"[a-zA-Z0-9_]{2,}", t))
    # 英文字符滑动窗口——2到4字窗口，覆盖"sup/up/port/grou/oup"等子串
    eng = "".join(re.findall(r"[a-z0-9]", t))
    for n in (2, 3, 4):
        for i in range(len(eng) - n + 1):
            tokens.add(eng[i:i + n])
    # 中文2字词
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    for i in range(len(chars) - 1):
        tokens.add(chars[i : i + 2])
    return {t for t in tokens if t}


def _query_tokens(text: str) -> set:
    """搜索分词：和_tokenize相同，但单字仅当输入只有一个中文字时才保留。"""
    tokens = _tokenize(text)
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    if len(chars) != 1:
        tokens -= set(chars)  # 去单字
    return tokens


def _parse_line(line: str) -> tuple:
    """返回 (ts, sender, text) 或 (None, None, None)。
    V2.4.0: 明文存储，直接返回原文。"""
    if " | " not in line:
        return None, None, None
    parts = line.strip().split(" | ", 2)
    if len(parts) < 3:
        return None, None, None
    return parts[0], parts[1], parts[2].strip()


def _journal_lines() -> int:
    if not os.path.exists(_SANDGLASS):
        return 0
    with open(_SANDGLASS, "r", encoding="utf-8", errors="replace") as f:
        return sum(1 for _ in f)


def _write_idx(idx, covered_lines: int = None):
    """Write idx dict to sandglass.idx file (atomic replace).

    头部记录构建时日志的物理行数 —— 这是判断索引是否过期的唯一可靠依据。
    旧实现拿"倒排里最大的行号"和"日志总行数"比，按记录索引之后前者是最后
    一条记录的首行号，永远小于后者，判据恒假。
    """
    if covered_lines is None:
        covered_lines = _journal_lines()
    tmp = _IDX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED BY NEXSANDGLASS — DO NOT EDIT\n")
        f.write(f"# covered_lines: {covered_lines}\n")
        f.write("# token:line_number,line_number,...\n")
        f.write("# delete this file and run rebuild_index() to regenerate\n")
        f.write("\n")
        for token in sorted(idx):
            f.write(f"{token}:{','.join(map(str, sorted(set(idx[token]))))}\n")
    os.replace(tmp, _IDX)


def idx_search(query: str, limit: int = 100) -> list:
    """IDX搜索：语言感知分词→倒排→返回候选行号列表"""
    try:
        idx = _sync_index()
        if not idx:
            rebuild_index()
            idx = _sync_index()
        if not idx:
            return []
        from nexsandglass.features.sandglass_think import _tokenize_for_density
        tokens = _tokenize_for_density(query)
        if not tokens:
            return []
        candidate_lines = set()
        for token in tokens:
            if token in idx:
                candidate_lines.update(idx[token])
        results = []
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                if n in candidate_lines:
                    ts, sender, text = _parse_line(line)
                    if ts and text:
                        results.append((n, ts, text))
                        if len(results) >= limit:
                            break
        return results
    except Exception:
        return []


def rebuild_index() -> int:
    """全量重建投石问路倒排索引。原子写。返回词条数。

    **按逻辑记忆索引，不按物理行。** 旧实现对续行 `if not ts: continue`，
    于是多行消息只有第一行进了倒排 —— 生产日志 85% 的内容从未被索引。
    token 映射到记录首行号（line_start），与 FTS5 的 id 保持一致。
    """
    global _idx_cache
    _idx_cache = None
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        from nexsandglass.core import memid
        idx = {}
        for rec in memid.parse_journal_records(_SANDGLASS):
            if memid.is_redacted(rec):
                continue                          # 已抹除：不进索引
            ln = rec["line_start"]
            for token in _tokenize(rec["text"]):
                idx.setdefault(token, []).append(ln)
        _write_idx(idx, _journal_lines())
        return len(idx)
    except Exception:
        logger.warning("sandglass: rebuild_index() failed", exc_info=True)
        return 0


def _sync_index() -> dict:
    """返回内存中的倒排索引 dict。带缓存，必要时增量补齐。

    修了两个既存缺陷：

    1. `_idx_mtime` 的赋值在函数末尾，而 `idx_max >= total` 分支提前 return，
       于是它永远停在 0 —— 下次进来 mtime 必不匹配，清缓存并 `return {}`。
       表现为**每隔一次调用就返回空索引**：倒排和 TF-IDF 两路在一半的查询里
       完全失效，而调用方看到空又会触发一次全量 rebuild。
    2. `if len(idx) > 5000: _idx_cache = {}; return {}` —— 生产索引有 20 万词条，
       这个"防膨胀"分支注定每次触发，索引永远缓存不住。

    现在：缓存键是日志物理行数（写进 idx 文件头），行数没变就直接返回缓存。
    """
    global _idx_cache, _idx_mtime

    try:
        if not os.path.exists(_SANDGLASS):
            _idx_cache, _idx_mtime = {}, 0
            return {}

        total = _journal_lines()
        # 缓存命中：日志行数未变 → 索引仍然是最新的
        if _idx_cache and _idx_mtime == total:
            return _idx_cache

        idx, covered, has_header, nonempty = {}, 0, False, False
        if os.path.exists(_IDX):
            with open(_IDX, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("#"):
                        if "covered_lines:" in line:
                            has_header = True
                            try:
                                covered = int(line.split(":", 1)[1].strip())
                            except ValueError:
                                covered, has_header = 0, False
                        continue
                    if ":" not in line:
                        continue
                    nonempty = True
                    t, rest = line.strip().split(":", 1)
                    nums = [int(x) for x in rest.split(",") if x]
                    if nums:
                        idx[t] = nums

        # 旧版 idx 文件没有 covered_lines 头，也不是按记录索引的。
        # 不能把它当成"覆盖了 0 行"去做增量 —— 那会把全部 token 重复追加进去，
        # posting list 直接翻倍。缺头 = 格式过期 = 全量重建。
        if nonempty and not has_header:
            logger.warning("sandglass: idx 为旧格式（无 covered_lines 头），全量重建")
            idx, covered = {}, 0
            from nexsandglass.core import memid
            for rec in memid.parse_journal_records(_SANDGLASS):
                if memid.is_redacted(rec):
                    continue
                for token in _tokenize(rec["text"]):
                    idx.setdefault(token, []).append(rec["line_start"])
            _write_idx(idx, total)
            _idx_cache, _idx_mtime = idx, total
            return idx

        if covered > total:
            logger.warning("sandglass: idx 覆盖行数(%d) > 日志行数(%d)，日志可能被截断，重建中", covered, total)
            from nexsandglass.features.sandglass_vault import rebuild_index as _rb
            _rb()
            return _sync_index()

        if covered < total:
            # 增量：只补新记录（按记录边界，不按物理行）
            from nexsandglass.core import memid
            for rec in memid.parse_journal_records(_SANDGLASS, from_line=covered + 1):
                if memid.is_redacted(rec):
                    continue
                for token in _tokenize(rec["text"]):
                    idx.setdefault(token, []).append(rec["line_start"])
            _write_idx(idx, total)

        _idx_cache, _idx_mtime = idx, total
        return idx
    except Exception:
        logger.warning("sandglass: _sync_index() failed", exc_info=True)
        return _idx_cache or {}

def search(query: str, limit: int = 10, month: str = "") -> list:
    """搜索沙漏。返回 [(行号, 时间, 明文), ...]。
    委托给 SearchRouter 三层架构——影子沙→投石问路→mmap。"""
    _enforce_runtime("vault.search")
    try:
        from nexsandglass.core.search_router import SearchRouter, ShadowSearch, Fts5Search, IdxSearch, TfidfSearch, MmapFallback
        router = SearchRouter(
            ShadowSearch(_SANDGLASS),
            Fts5Search(),
            IdxSearch(_SANDGLASS, _IDX),
            TfidfSearch(),
            MmapFallback(_SANDGLASS)
        )
        return router.search(query, limit)
    except Exception:
        return _legacy_search(query, limit, month)


def _legacy_search(query, limit, month):
    """Fallback: mmap全量扫描 → FTS5精排。只在SearchRouter不可用时触发。"""
    try:
        mmap_results = _mmap_search(query, 500, month)
        if mmap_results:
            from nexsandglass.core.sandglass_sqlite import search_in, sync_incremental
            sync_incremental()
            line_nums = [r[0] for r in mmap_results[:500]]
            ranked = search_in(line_nums, query)
            if ranked:
                return [(r[0], r[1], r[2]) for r in ranked[:limit]]
        return [(r[0], r[1], r[2]) for r in mmap_results[:limit]]
    except Exception:
        logger.warning("sandglass: search(%r) failed", query, exc_info=True)
        return []



def recent(n: int = 10) -> list:
    _enforce_runtime("vault.recent")
    """最近 N 条。[(行号, 时间, 明文), ...]。

    返回物理行号（与 search/FTS5 的 id 一致），从文件尾部取最后 N 条有效消息。
    """
    try:
        if n <= 0 or not os.path.exists(_SANDGLASS):
            return []
        results = []
        with open(_SANDGLASS, "r", encoding="utf-8", errors="ignore") as f:
            for ln, line in enumerate(f, 1):
                ts, sender, text = _parse_line(line)
                if ts:
                    results.append((ln, ts, text))
        return results[-n:]
    except Exception:
        logger.warning("sandglass: recent(%d) failed", n, exc_info=True)
        return []


def count() -> int:
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            return sum(1 for _ in f)
    except Exception:
        logger.warning("sandglass: count() failed", exc_info=True)
        return 0


def _mmap_search(query: str, limit: int, month: str, stage_filter: bool = False) -> list:
    """三级降级：mmap 直接内存搜索。stage_filter=True 时只扫当前阶段+上一阶段。"""
    results = []
    try:
        # 阶段过滤——缩小扫描范围
        scan_months = [month]
        if stage_filter:
            try:
                from nexsandglass.features.sandglass_think import _current_stage, stage_list
                current = _current_stage()
                scan_months = [current]
                stages = stage_list()
                if len(stages) >= 2:
                    scan_months.append(stages[-2].get("name", current))
            except: pass
        with open(_SANDGLASS, "rb") as f:
            with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
                line_start = 0; line_num = 0
                while line_start < len(mm):
                    line_end = mm.find(b"\n", line_start)
                    if line_end == -1: line_end = len(mm)
                    line_num += 1
                    line = mm[line_start:line_end].decode("utf-8", errors="replace")
                    ts, sender, text = _parse_line(line)
                    if ts and query.lower() in text.lower():
                        if not month or ts.startswith(month):
                            results.append((line_num, ts, text))
                            if limit > 0 and len(results) >= limit: break
                    line_start = line_end + 1
    except Exception:
        pass
    return results


# ═══════════════════════════════════════════════
# 时间回溯
# ═══════════════════════════════════════════════

def timeline(query: str) -> dict:
    """时间回溯——按年份分层返回关键词的演变轨迹。"""
    try:
        all_results = search(query, limit=10000)
        if not all_results:
            return {}
        # 按行号升序（时间顺序），而非 reverse search 的匹配数排序
        all_results.sort(key=lambda x: x[0])

        years = {}
        for ln, ts, text in all_results:
            year = ts[:4]
            if year not in years:
                years[year] = {"count": 0, "earliest": text, "earliest_at": ts, "latest": text, "latest_at": ts}
            years[year]["count"] += 1
            years[year]["latest"] = text
            years[year]["latest_at"] = ts

        result = {}
        for year in sorted(years):
            y = years[year]
            result[year] = {"count": y["count"], "earliest": y["earliest"], "earliest_at": y["earliest_at"],
                            "latest": y["latest"], "latest_at": y["latest_at"]}
        return result
    except Exception:
        logger.warning("sandglass: timeline(%r) failed", query, exc_info=True)
        return {}

# ═══════════════════════════════════════════════
# 沙漏导入/合并 —— V2.9.3-dev
# ═══════════════════════════════════════════════

def sandglass_import(source_path: str, source_format: str = "sandglass") -> dict:
    """导入外部对话记录到沙漏。支持格式:
    - sandglass: 同格式沙漏导出 (时间戳 | 发送者 | 文本)
    - chatgpt: ChatGPT JSON 导出
    - claude: Claude 对话 JSON 导出
    - plain: 纯文本，每行一条
    
    返回 {imported: N, skipped: N, total: N}
    """
    imported = 0
    skipped = 0
    
    try:
        if source_format == "sandglass":
            imported, skipped = _import_sandglass(source_path)
        elif source_format in ("chatgpt", "claude"):
            imported, skipped = _import_json_convo(source_path, source_format)
        elif source_format == "plain":
            imported, skipped = _import_plain(source_path)
        else:
            return {"error": f"不支持格式: {source_format}"}
        
        # 导入后重建索引
        try:
            from nexsandglass.core.sandglass_sqlite import sync_incremental
            sync_incremental()
        except: pass
        
        return {"imported": imported, "skipped": skipped, "total": imported + skipped}
    except Exception as e:
        logger.error(f"导入失败: {e}")
        return {"error": str(e), "imported": imported, "skipped": skipped}




def sandglass_export(output_path: str = None, limit: int = None, month: str = "") -> str:
    """导出沙漏为可迁移文件。默认导出全部。
    返回导出文件路径。
    """
    if output_path is None:
        from nexsandglass.core.sandglass_paths import _NB
        output_path = os.path.join(_NB, "sandglass_export.txt")
    
    lines = []
    if os.path.exists(_SANDGLASS):
        with open(_SANDGLASS, "r", encoding="utf-8") as src:
            for line in src:
                if month and not line.startswith(month[:7]):
                    continue
                lines.append(line)
                if limit and len(lines) >= limit:
                    break
        
        # 取最后 limit 条（从全量读取后截断）
        if limit and len(lines) > limit:
            lines = lines[-limit:]
    
    with open(output_path, "w", encoding="utf-8") as dst:
        dst.writelines(lines)
    
    return output_path

def _import_sandglass(source_path: str) -> tuple:
    """导入同格式沙漏——按行号去重"""
    # 读已有沙漏的时间戳集合
    existing_ts = set()
    if os.path.exists(_SANDGLASS):
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for line in f:
                if " | " in line:
                    ts = line.split(" | ")[0].strip()
                    existing_ts.add(ts)
    
    imported = 0
    skipped = 0
    with open(source_path, "r", encoding="utf-8") as src:
        for line in src:
            line = line.strip()
            if not line or not line.startswith("20"):  # 跳过非时间戳行
                continue
            if " | " not in line:
                continue
            ts = line.split(" | ")[0].strip()
            if ts in existing_ts:
                skipped += 1
                continue
            
            # 追加到沙漏
            try:
                from nexsandglass.core.sandglass_log import log_message as _log_message
                parts = line.split(" | ", 2)
                if len(parts) >= 3:
                    sender = parts[1].strip()
                    text = parts[2].strip()
                    _log_message(text, sender)
                    existing_ts.add(ts)
                    imported += 1
            except Exception:
                skipped += 1
    
    return imported, skipped


def _import_json_convo(source_path: str, fmt: str) -> tuple:
    """导入 ChatGPT/Claude JSON 导出"""
    import json
    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    imported = 0
    skipped = 0
    
    # ChatGPT 格式: [{"mapping": {...}}, ...]
    # Claude 格式: [{"chat_messages": [...]}, ...]
    messages = []
    if fmt == "chatgpt":
        for conv in (data if isinstance(data, list) else [data]):
            mapping = conv.get("mapping", {})
            for mid, node in sorted(mapping.items(), key=lambda x: x[1].get("create_time", 0) if x[1] else 0):
                if node and node.get("message"):
                    msg = node["message"]
                    role = msg.get("author", {}).get("role", "user")
                    content = "".join(p for p in (msg.get("content", {}).get("parts", []) if isinstance(msg.get("content"), dict) else []) if isinstance(p, str))
                    if content:
                        messages.append((role, content))
    elif fmt == "claude":
        for conv in (data if isinstance(data, list) else [data]):
            for msg in conv.get("chat_messages", []):
                role = msg.get("sender", "user")
                content = msg.get("text", "")
                if content:
                    messages.append((role, content))
    
    for role, text in messages:
        try:
            from nexsandglass.core.sandglass_log import log_message as _log_message
            sender = "user" if role in ("user", "human") else "agent"
            _log_message(text, sender)
            imported += 1
        except Exception:
            skipped += 1
    
    return imported, skipped


def _import_plain(source_path: str) -> tuple:
    """导入纯文本——每行一条用户消息"""
    imported = 0
    skipped = 0
    with open(source_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                from nexsandglass.core.sandglass_log import log_message as _log_message
                _log_message(line, "user")
                imported += 1
            except Exception:
                skipped += 1
    return imported, skipped
